version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: knexDB
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: knexDB
    volumes:
      - postgres-17:/var/lib/postgresql/data

volumes:
  postgres-17:
